server:
  port: 8088
spring:
  profiles:
    active: dev
    #active: prod
  cache:
    # 关键配置：指定使用复合缓存管理器
    type: generic
    # 定义缓存的名称，以及它们各自的配置
    cache-names: article, tag, category # 列出您项目中所有用到的缓存区名称

    # Caffeine (一级缓存) 的具体配置
    caffeine:
      spec: > # 使用 spec 字符串进行详细配置
        initialCapacity=50,
        maximumSize=500,
        expireAfterWrite=10m,
        recordStats
        # initialCapacity: 初始容量
        # maximumSize: 最大容量，超过会自动淘汰
        # expireAfterWrite=10m: 写入后10分钟过期
        # recordStats: 开启统计功能，便于监控

    # Redis (二级缓存) 的具体配置
    redis:
      time-to-live: 60m # Redis缓存过期时间，通常比Caffeine长，比如60分钟
      cache-null-values: true # 允许缓存null值，防止缓存穿透
      key-prefix: "RuyuBlogCache:" # 为所有缓存key加一个统一的前缀，便于管理
      use-key-prefix: true